#!/bin/sh

PROJECT_NAME=vectorsoft-server
PROJECT_DN=${PROJECT_NAME}.test
ARG_1=$1
# mkdir -p certs
# mkcert -key-file certs/${PROJECT_NAME}-ssl.key -cert-file certs/${PROJECT_NAME}-ssl.crt ${PROJECT_DN}

./generate-nodesource
docker build -t vectorsoft-container .

if [ $ARG_1 -a $ARG_1 = 'start' ]
	then docker compose up -d && sleep 2 && docker compose logs -f vectorsoft
fi
